[package]
name = "pgcd"
version = "0.1.0"
authors = ["Bastien Duplessier <bastien.duplessier@gmail.com>"]

[dependencies]
iron = "0.6.0"
mime = "0.2.6"
router = "0.6.0"
urlencoded = "0.6.0"
params = "0.8.0"
